######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "Home"
theme = "hargo"
summaryLength = "20"
paginate = 12
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  link = "plugins/image-zoom.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"
  [[params.plugins.js]]
  link = "plugins/form_submission_handler.js"
  [[params.plugins.js]]
  link = "plugins/image-zoom.min.js"

############################## navigation ###############################
[menu]
  
  [[menu.main]]
    name = "Home"
    url = "/categories/destacados"
    weight = 1

  [[menu.main]]
  name = "Aros"
  identifier = "aros"
  weight = 2

  [[menu.main]]
  name = "Dijes"
  identifier = "dijes"
  weight = 3
  
  [[menu.main]]
  name = "Colgantes"
  identifier = "colgantes"
  weight = 4
  
  [[menu.main]]
  name = "Pulseras"
  identifier = "pulseras"
  weight = 5

  [[menu.main]]
  name = "Anillos"
  identifier = "anillos"
  weight = 6

 [[menu.main]]
  name = "Conjuntos"
  identifier = "conjuntos"
  weight = 7

 [[menu.main]]
  name = "Promos"
  URL = "promos"
  weight = 8

  [[menu.main]]
  name = "Preguntas frecuentes"
  URL = "faq"
  weight = 9

  [[menu.main]]
  name = "Nosotros"
  URL = "nosotros"
  weight = 10

  [[menu.main]]
  name = "Contacto"
  URL = "contacto"
  weight = 11



  ############# footer menu #############
  [[menu.footer]]
  name = "Preguntas frecuentes"
  URL = "faq"
  weight = 2
  
  [[menu.footer]]
  name = "Nosotros"
  URL = "nosotros"
  weight = 3

  [[menu.footer]]
  name = "Contacto"
  URL = "contacto"
  weight = 4


#################### default parameters ################################
[params]
logo = "images/logo_mediano.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
banner = "images/banner_centro.png"

# Contact Information
mobile = "+5491158104619"
email = "hola.in.plata@gmail.com"
location = "Caballito, CABA"

# Contact Form
[params.contact]
formAction = "https://script.google.com/macros/s/AKfycbyAXift3Wqrs3LHrNmgvrecvinLURxhmig0RJp7zx342TihJHY/exec"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Social Site
  [[params.social]]
  icon = "ti-instagram"
  link = "https://instagram.com/in.plata_"

